import Foundation

struct SampleData {
    static let books: [Book] = [

        // MARK: - Recommended
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000001")!,
            title: "The Art of Focus",
            author: "Arjun Patel",
            description: "A transformative guide to sharpening your attention and achieving deep work in a distracted world. Learn proven techniques that top performers use to accomplish more in less time.",
            price: 399,
            originalPrice: 549,
            format: .paperback,
            categories: ["Self-help", "Philosophy"],
            coverColor: .purple,
            rating: 4.6,
            reviewCount: 1243,
            pageCount: 256,
            publisher: "Mindful Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -6, to: Date())!,
            isbn: "978-8193423011",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: true
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000002")!,
            title: "The Art of Learning",
            author: "Raj Patel",
            description: "Discover the secrets behind rapid skill acquisition and lifelong mastery. This groundbreaking book draws from neuroscience and the habits of world-class learners.",
            price: 259,
            originalPrice: 349,
            format: .paperback,
            categories: ["Self-help", "Science"],
            coverColor: .blue,
            rating: 4.4,
            reviewCount: 987,
            pageCount: 224,
            publisher: "Horizon Books",
            publishDate: Calendar.current.date(byAdding: .month, value: -9, to: Date())!,
            isbn: "978-8193423012",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: true
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000003")!,
            title: "The Path to Success",
            author: "James Wright",
            description: "An inspiring roadmap for anyone who wants to achieve meaningful goals. Wright shares hard-won wisdom through compelling personal stories and actionable frameworks.",
            price: 359,
            originalPrice: 499,
            format: .hardcover,
            categories: ["Self-help", "Biography"],
            coverColor: .green,
            rating: 4.5,
            reviewCount: 2105,
            pageCount: 312,
            publisher: "Summit Publishing",
            publishDate: Calendar.current.date(byAdding: .month, value: -3, to: Date())!,
            isbn: "978-8193423013",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: true
        ),

        // MARK: - Bestsellers
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000004")!,
            title: "The Midnight Hour",
            author: "James Adams",
            description: "A chilling mystery set in a small English village where secrets buried for decades resurface after a single fateful night. Adams delivers twists that will keep you reading until dawn.",
            price: 299,
            originalPrice: 399,
            format: .paperback,
            categories: ["Mystery", "Drama"],
            coverColor: .indigo,
            rating: 4.7,
            reviewCount: 3456,
            pageCount: 368,
            publisher: "Nocturne Books",
            publishDate: Calendar.current.date(byAdding: .month, value: -18, to: Date())!,
            isbn: "978-8193423014",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000005")!,
            title: "Beneath the Stars",
            author: "Jessica Martin",
            description: "A sweeping romance that spans three continents and two decades. Martin weaves together love, loss and longing in a story that celebrates the enduring power of human connection.",
            price: 499,
            originalPrice: 649,
            format: .hardcover,
            categories: ["Romance", "Historical"],
            coverColor: .pink,
            rating: 4.8,
            reviewCount: 5621,
            pageCount: 432,
            publisher: "Starlight Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -24, to: Date())!,
            isbn: "978-8193423015",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000006")!,
            title: "The Final Frontier",
            author: "Laura Mitchell",
            description: "An ambitious science fiction saga following the crew of humanity's first interstellar mission. Mitchell masterfully blends hard science with profound questions about what it means to be human.",
            price: 359,
            originalPrice: nil,
            format: .ebook,
            categories: ["Science Fiction", "Science"],
            coverColor: .teal,
            rating: 4.6,
            reviewCount: 2890,
            pageCount: 496,
            publisher: "Cosmos Publishing",
            publishDate: Calendar.current.date(byAdding: .month, value: -12, to: Date())!,
            isbn: "978-8193423016",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: false
        ),

        // MARK: - New Launches
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000007")!,
            title: "Joy of Minimalism",
            author: "Daniel Reed",
            description: "Declutter your home, mind and digital life with this beautifully practical guide. Reed offers a compassionate, step-by-step approach to living with intention and less.",
            price: 149,
            originalPrice: 199,
            format: .ebook,
            categories: ["Self-help", "Philosophy"],
            coverColor: .yellow,
            rating: 4.3,
            reviewCount: 234,
            pageCount: 192,
            publisher: "Clear Path Books",
            publishDate: Calendar.current.date(byAdding: .day, value: -14, to: Date())!,
            isbn: "978-8193423017",
            isBestseller: false,
            isNewLaunch: true,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000008")!,
            title: "The Vanishing House",
            author: "Clara Nelson",
            description: "A young girl discovers that her family's ancestral home hides a terrifying secret that has been passed down through generations. A masterful blend of gothic atmosphere and psychological suspense.",
            price: 99,
            originalPrice: 149,
            format: .paperback,
            categories: ["Mystery", "Young Adult"],
            coverColor: .red,
            rating: 4.2,
            reviewCount: 178,
            pageCount: 288,
            publisher: "Shadow House Publishing",
            publishDate: Calendar.current.date(byAdding: .day, value: -7, to: Date())!,
            isbn: "978-8193423018",
            isBestseller: false,
            isNewLaunch: true,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000009")!,
            title: "The Lost Kitten",
            author: "Emily Parker",
            description: "A heartwarming children's story about a kitten who wanders far from home and discovers friendship in the most unexpected places. Beautifully illustrated and perfect for bedtime.",
            price: 339,
            originalPrice: 399,
            format: .hardcover,
            categories: ["Children's"],
            coverColor: .orange,
            rating: 4.9,
            reviewCount: 512,
            pageCount: 48,
            publisher: "Little Paws Press",
            publishDate: Calendar.current.date(byAdding: .day, value: -3, to: Date())!,
            isbn: "978-8193423019",
            isBestseller: false,
            isNewLaunch: true,
            isRecommended: false
        ),

        // MARK: - Additional catalogue books
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000010")!,
            title: "Echoes of Tomorrow",
            author: "Samuel Grant",
            description: "A gripping dystopian thriller set in 2087 where memories can be bought and sold. One archivist stumbles upon a memory that could tear society apart.",
            price: 429,
            originalPrice: nil,
            format: .ebook,
            categories: ["Science Fiction", "Fantasy"],
            coverColor: .purple,
            rating: 4.4,
            reviewCount: 1102,
            pageCount: 414,
            publisher: "Future Ink",
            publishDate: Calendar.current.date(byAdding: .month, value: -5, to: Date())!,
            isbn: "978-8193423020",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: true
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000011")!,
            title: "Dragon's Cradle",
            author: "Priya Sharma",
            description: "An epic fantasy where dragon riders are the last line of defence against an ancient darkness. The first installment in the breathtaking Skyborn Chronicles series.",
            price: 549,
            originalPrice: 699,
            format: .hardcover,
            categories: ["Fantasy", "Young Adult"],
            coverColor: .red,
            rating: 4.7,
            reviewCount: 3201,
            pageCount: 512,
            publisher: "Realm Books",
            publishDate: Calendar.current.date(byAdding: .month, value: -8, to: Date())!,
            isbn: "978-8193423021",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000012")!,
            title: "The Forgotten Empire",
            author: "Michael Torres",
            description: "An immersive historical saga set during the twilight of the Byzantine Empire. Torres brings a lost civilisation to vivid life with meticulous research and compelling characters.",
            price: 479,
            originalPrice: 599,
            format: .paperback,
            categories: ["Historical", "Drama"],
            coverColor: .brown,
            rating: 4.5,
            reviewCount: 876,
            pageCount: 576,
            publisher: "Epoch Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -15, to: Date())!,
            isbn: "978-8193423022",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000013")!,
            title: "Mindful Mornings",
            author: "Ananya Kapoor",
            description: "Transform the first hour of your day with 30 science-backed rituals that reduce stress, boost creativity and set a positive tone for everything that follows.",
            price: 249,
            originalPrice: 329,
            format: .paperback,
            categories: ["Self-help", "Memoir"],
            coverColor: .green,
            rating: 4.6,
            reviewCount: 1456,
            pageCount: 208,
            publisher: "Serenity Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -10, to: Date())!,
            isbn: "978-8193423023",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: true
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000014")!,
            title: "Spice Routes",
            author: "Leila Hassan",
            description: "A culinary journey through the ancient spice trade routes of Asia and the Middle East, featuring 80 heirloom recipes and stunning food photography.",
            price: 699,
            originalPrice: 899,
            format: .hardcover,
            categories: ["Cooking", "Travel", "Historical"],
            coverColor: .orange,
            rating: 4.8,
            reviewCount: 2340,
            pageCount: 320,
            publisher: "Savour Books",
            publishDate: Calendar.current.date(byAdding: .month, value: -4, to: Date())!,
            isbn: "978-8193423024",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000015")!,
            title: "Wanderlust Diaries",
            author: "Sofia Reyes",
            description: "A vivid travel memoir chronicling one woman's solo journey through 40 countries in 365 days. Funny, honest and deeply moving — a love letter to the open road.",
            price: 319,
            originalPrice: nil,
            format: .paperback,
            categories: ["Travel", "Memoir"],
            coverColor: .teal,
            rating: 4.3,
            reviewCount: 678,
            pageCount: 344,
            publisher: "Compass Books",
            publishDate: Calendar.current.date(byAdding: .month, value: -7, to: Date())!,
            isbn: "978-8193423025",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: true
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000016")!,
            title: "Binary Hearts",
            author: "Kevin Okafor",
            description: "A witty, heartfelt graphic novel about two AI researchers who fall in love while trying to teach robots how to feel. A modern classic of science fiction romance.",
            price: 389,
            originalPrice: 449,
            format: .paperback,
            categories: ["Comics & Graphic Novels", "Romance", "Science Fiction"],
            coverColor: .blue,
            rating: 4.5,
            reviewCount: 1789,
            pageCount: 248,
            publisher: "Panel Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -11, to: Date())!,
            isbn: "978-8193423026",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000017")!,
            title: "Songs of the River",
            author: "Natasha Ivanova",
            description: "A collection of 60 luminous poems exploring the themes of memory, migration and belonging. Winner of the national poetry award.",
            price: 199,
            originalPrice: 249,
            format: .paperback,
            categories: ["Poetry"],
            coverColor: .pink,
            rating: 4.4,
            reviewCount: 423,
            pageCount: 128,
            publisher: "Verse Press",
            publishDate: Calendar.current.date(byAdding: .day, value: -20, to: Date())!,
            isbn: "978-8193423027",
            isBestseller: false,
            isNewLaunch: true,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000018")!,
            title: "The Quantum Mind",
            author: "Dr. Alan Pierce",
            description: "A Nobel laureate explains quantum consciousness theory for the general reader. Challenging, accessible and ultimately awe-inspiring — science writing at its finest.",
            price: 449,
            originalPrice: 599,
            format: .hardcover,
            categories: ["Science", "Philosophy"],
            coverColor: .indigo,
            rating: 4.6,
            reviewCount: 1102,
            pageCount: 396,
            publisher: "Academia Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -2, to: Date())!,
            isbn: "978-8193423028",
            isBestseller: false,
            isNewLaunch: true,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000019")!,
            title: "Nihongo for Life",
            author: "Yuki Tanaka",
            description: "The most practical and engaging Japanese language learning book available. Tanaka's unique immersion-first method gets you conversational in 90 days.",
            price: 499,
            originalPrice: 649,
            format: .paperback,
            categories: ["Language Learning"],
            coverColor: .red,
            rating: 4.7,
            reviewCount: 2987,
            pageCount: 480,
            publisher: "Lingua Press",
            publishDate: Calendar.current.date(byAdding: .month, value: -6, to: Date())!,
            isbn: "978-8193423029",
            isBestseller: true,
            isNewLaunch: false,
            isRecommended: false
        ),
        Book(
            id: UUID(uuidString: "00000000-0000-0000-0000-000000000020")!,
            title: "The Prophet's Garden",
            author: "Ibrahim Al-Rashid",
            description: "An intimate and scholarly exploration of mystical traditions across the world's major religions, revealing the shared spiritual roots beneath their diverse expressions.",
            price: 375,
            originalPrice: nil,
            format: .hardcover,
            categories: ["Religion", "Philosophy"],
            coverColor: .green,
            rating: 4.5,
            reviewCount: 567,
            pageCount: 304,
            publisher: "Wisdom Books",
            publishDate: Calendar.current.date(byAdding: .month, value: -16, to: Date())!,
            isbn: "978-8193423030",
            isBestseller: false,
            isNewLaunch: false,
            isRecommended: false
        )
    ]
}
